name: Continuous Deployment

on:
  push:
    branches: '*'

jobs:
  deploy:
    name: Deploy to Heroku
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login / Build / Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ 'smart-greenhouse-middleware' }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
          heroku container:push -a $HEROKU_APP_NAME web
          heroku container:release -a $HEROKU_APP_NAME web
